
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host-nginx
  template:
    metadata:
      labels:
        app: host-nginx
    spec:
      nodeName: srv653681.hstgr.cloud   # 👈 change to your node name
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-conf-d
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf
          hostPath:
            path: /data/k3s/nginx
            type: Directory
        - name: nginx-conf-d
          hostPath:
            path: /data/k3s/nginx/conf.d
            type: Directory
