blank_issues_enabled: false  # disables the "Open a blank issue" button
contact_links:
  - name: 💬 General Question
    url: https://github.com/learning-devops2711-org/deploy-tenant/discussions
    about: Ask a question or start a discussion here.
