name: Feature Request
description: Suggest a new feature or enhancement.
title: "[FEATURE] <short description>"
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? Let us know by filling out this form.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem?
      placeholder: "I’m always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
