apiVersion: v1
kind: Namespace
metadata:
  name: strapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: learningdevops2711/strapi:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  namespace: strapi
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 1337
      protocol: TCP
  selector:
    app: strapi
