apiVersion: v1
kind: Namespace
metadata:
  name: strapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      dnsPolicy: "Default"
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: strapi
          image: strapi:v1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0  # Run as root so we can install Docker CLI if needed
          ports:
            - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  namespace: strapi
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 1337
      protocol: TCP
  selector:
    app: strapi
