
apiVersion: v1
kind: Namespace
metadata:
  name: tenant4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: tenant4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: traefik/whoami
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: tenant4
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
