name: Checkout Multiple Repos

on:
  workflow_dispatch:  # Or use push, pull_request, etc.

jobs:
  multi-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Print repo info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Owner: ${{ github.repository_owner }}"
          echo "Actor (who triggered): ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Workflow: ${{ github.workflow }}"

      # Checkout main repository
      - name: Checkout main repo
        uses: actions/checkout@v4

      # Checkout a private repo (requires token)
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/hello-world-spring-boot-docker
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # must have repo access
          path: hello-world-spring-boot-docker

      # Checkout a private repo (requires token)
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/java-hello-world-with-maven
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # must have repo access
          path: java-hello-world-with-maven

