name: Sync Folder to Remote Server

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_REMOTE }} >> ~/.ssh/known_hosts

      - name: Sync folder to server
        run: |
          rsync -avz ./nginx/ root@${{secrets.SSH_REMOTE}}:/data/k3s/nginx
          rsync -avz ./stacks/ root@${{secrets.SSH_REMOTE}}:/data/k3s/stacks
